done
Sam130687/react-20231109 pull request #6
Opened 2023-12-02 17:35 UTC by Sam130687

Проверьте пожалуйста

2023-12-04 14:51 UTC, SArchieEdu requested changes
После разбора нужны будут правки

2023-12-04 14:51 UTC, SArchieEdu commented on src/components/dish/component.jsx
> +                    className={{action: forms.theme === "light" ? styles.blackButton : styles.lightButton}}/>
не, родитель не должен знать о устройстве дочернего

2023-12-05 08:03 UTC, Sam130687 commented on src/components/dish/component.jsx
> +                    className={{action: forms.theme === "light" ? styles.blackButton : styles.lightButton}}/>
Исправлено

2023-12-07 15:05 UTC, SArchieEdu approved these changes

2023-12-07 15:05 UTC, SArchieEdu commented on src/components/theme/context.jsx
> +  forms: { theme: {} },
а зачем forms

2023-12-07 15:06 UTC, Sam130687 commented on src/components/theme/context.jsx
> +  forms: { theme: {} },
А уберу )

2023-12-08 09:42 UTC, merged